# @package _global_
_target_: mlprof.configs.ExperimentConfig

backend: DDP
seed: 1234
ds_config_path: null
precision: 'float32'

# Specify here default configuration
# Ordering determines precedence, i.e.
# the order determines the order in which options are overridden
defaults:
  - _self_
  - network: default.yaml
  - data: default.yaml
  - trainer: default.yaml
  - wandb: default.yaml

  # Experiment configs allow for version control of specific hyperparameters
  # e.g. the best hyperparameters for a given model and datamodule
  # - experiment: null
  - optional local: default.yaml

   # debugging config
  - debug: null

  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: custom


# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with
# `python train.py tags="[first_tag, second_tag]"`
# tags: null

# ckpt_path: null

hydra:
  job:
    chdir: true

# # path to original working directory
# # hydra hijacks working directory by changing it to the new log directory
# # so its useful to have this path as a special variable
# # https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
# work_dir: ${hydra:runtime.cwd}
# # path to folder with data
# data_dir: ${work_dir}/datasets/
